FROM python:3.13.3-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    cron rsync openssh-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY models /app/models

COPY Crawler/requirements.txt /app/crawler-requirements.txt
RUN pip install --no-cache-dir -r crawler-requirements.txt

COPY Analyser/requirements.txt /app/analyser-requirements.txt
RUN pip install --no-cache-dir -r analyser-requirements.txt

COPY Crawler/ /app/Crawler/
COPY Analyser/ /app/Analyser/
COPY Shared/ /app/Shared/
COPY Config/app-config.json /app/Config/app-config.json

COPY pipeline-entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
