spring:
  application:
    name: Back


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations:
        - file:../Schema/01-user.sql
        - file:../Schema/02-profiles.sql
        - file:../Schema/03-user-settings.sql
        - file:../Schema/04-sentiment-average.sql
  
  
server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ReleaseBack.Back.entity
  configuration:
    map-underscore-to-camel-case: true
